//Even Fibonacci numbers
//Problem 2
//
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be :
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.

#include <iostream>

using namespace std;

int main() {

	unsigned int sum = 0;

	unsigned int term1 = 1;
	unsigned int term2 = 2;

	unsigned int oldt2;

	while (term2 < 4000000)
	{
		if (term2 % 2 == 0) {
			sum += term2;
			cout << term2 << endl;
		}

		oldt2 = term2;

		term2 = term1 + term2;
		term1 = oldt2;
	}

	cout << "sum = " << sum << endl;

	cin.get();
	return 0;
}

// answer: 4613732
